import Link from "next/link";

const reportCards = [
  {
    title: "Patient Report",
    description: "View patient registration, admission and discharge information.",
    icon: "👥",
  },
  {
    title: "Vitals Report",
    description: "Review recorded patient vitals and identify abnormal readings.",
    icon: "❤️",
  },
  {
    title: "Attendance Report",
    description: "Review staff attendance and daily attendance records.",
    icon: "🕐",
  },
  {
    title: "Payments Report",
    description: "View payments received, outstanding balances and billing activity.",
    icon: "💳",
  },
  {
    title: "Invoice Report",
    description: "Review invoices generated by the rehabilitation centre.",
    icon: "🧾",
  },
  {
    title: "Deleted Patients",
    description: "Review patients moved to the deleted/archive section.",
    icon: "🗑️",
  },
  {
    title: "Patient Files & Diagnostics",
    description:
      "Manage patient diagnostic reports, lab reports, scans, prescriptions and other documents.",
    icon: "📁",
    href: "/reports/patient-files",
  },
];

export default function ReportsPage() {
  return (
    <main className="min-h-screen bg-slate-100">
      <div className="mx-auto max-w-7xl p-6">
        <div className="mb-6 flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
          <div>
            <h1 className="text-3xl font-bold text-slate-900">
              Reports
            </h1>
            <p className="mt-1 text-sm text-slate-500">
              Rehabilitation centre reports and summaries
            </p>
          </div>

          <Link
            href="/"
            className="inline-flex w-fit items-center rounded-xl border border-slate-300 bg-white px-4 py-2 text-sm font-medium text-slate-700 shadow-sm hover:bg-slate-50"
          >
            ← Back to Dashboard
          </Link>
        </div>

        <section className="mb-6 rounded-2xl bg-white p-6 shadow-sm">
          <h2 className="text-xl font-bold text-slate-900">
            Reports Centre
          </h2>
          <p className="mt-1 text-sm text-slate-500">
            Select a report to review information from your rehabilitation
            centre.
          </p>
        </section>

        <section className="grid gap-5 md:grid-cols-2 xl:grid-cols-3">
          {reportCards.map((report) => (
            <div
              key={report.title}
              className="rounded-2xl bg-white p-6 shadow-sm transition hover:-translate-y-0.5 hover:shadow-md"
            >
              <div className="mb-4 flex h-12 w-12 items-center justify-center rounded-xl bg-blue-50 text-2xl">
                {report.icon}
              </div>

              <h3 className="text-lg font-bold text-slate-900">
                {report.title}
              </h3>

              <p className="mt-2 text-sm leading-6 text-slate-500">
                {report.description}
              </p>

              {report.href ? (
                <Link
                  href={report.href}
                  className="mt-5 inline-flex rounded-xl bg-blue-600 px-4 py-2 text-sm font-medium text-white hover:bg-blue-700"
                >
                  Open Report
                </Link>
              ) : (
                <button
                  type="button"
                  className="mt-5 rounded-xl bg-blue-600 px-4 py-2 text-sm font-medium text-white hover:bg-blue-700"
                >
                  Open Report
                </button>
              )}
            </div>
          ))}
        </section>

        <section className="mt-6 rounded-2xl bg-white p-6 shadow-sm">
          <h2 className="text-lg font-bold text-slate-900">
            Future Report Features
          </h2>

          <div className="mt-4 grid gap-3 text-sm text-slate-600 md:grid-cols-2">
            <div>• Date-range filtering</div>
            <div>• Patient-wise reports</div>
            <div>• Staff attendance summaries</div>
            <div>• Vitals history reports</div>
            <div>• Payment and outstanding reports</div>
            <div>• Printable PDF reports</div>
          </div>
        </section>
      </div>
    </main>
  );
}
